name: Render and Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:
    name: Render and deploy protocol and API docs
    timeout-minutes: 30
    runs-on: buildjet-4vcpu-ubuntu-2004
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          lfs: true
